development:
  adapter: postgresql
  encoding: unicode
  database: wedding_development
  pool: 5
  username: efatsi
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: wedding_test
  pool: 5
  username: efatsi
  password:
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: wedding_production
  pool: 5
  username: efatsi
  password:
